# Generated by Django 4.2.11 on 2024-04-23 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='s_link',
            new_name='slug',
        ),
    ]
