# Generated by Django 4.2.11 on 2024-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=250),
        ),
    ]
